Updates to Floquet drive, two-level qubit, and Kerr nonlinear oscillator, as well as some single-charge stuff
EQuS/qcsys pull request #6
Opened 2024-08-01 22:52 UTC by shoumikdc

All these qubits are now updated to work with the standard truncation scheme in qcsys

2024-08-06 00:33 UTC, shoumikdc commented
Summary: 
- Updated transmon qubit to have a gate-offset charge `ng`. By default `ng = 0` to ensure backward compatibility with sims where `ng` was not specified. 
- Added single-electron charge basis mode to the transmon qubit. 
- Updated Floquet drive to use `jnp2jqt` during operator construction.
- Added Floquet tutorial.
- Minor fixes to Kerr nonlinear oscillator (KNO) and IdealQubit.

2024-08-06 04:01 UTC, Phionx requested changes
Mostly LGTM! Just need to address some minor comments. Also, run all the tutorial notebooks to confirm everything still works as before.

2024-08-06 07:40 UTC, shoumikdc commented on qcsys/devices/drive.py
>          M_max = self.M_max
This is done in the `6-floquet` tutorial and in some of my other simulations! Checked that the drive indeed works with `jit` (and also `vmap` etc).

2024-08-06 07:41 UTC, shoumikdc commented on qcsys/devices/kno.py
> -    @classmethod
Added!

2024-08-06 07:41 UTC, shoumikdc commented on qcsys/devices/ideal_qubit.py
> -        """ Written in the linear basis. """
Added!

2024-08-06 08:04 UTC, shoumikdc commented
Added params validation for KNO and IdealQubit and checked that drive plays nicely with jit in functions that construct driven systems. 

Checked that all previous tutorials run and give expected results!
Since the transmon qubit had the most significant changes, also did a deeper dive into differences between the old and new versions of the Hamiltonian construction. When printed to 8 decimal places in the notebook, the eigenvalues look the same - so the new version matches up. I will note that when I looked at the result to more sig figs, I found that the Hamiltonians are slightly different on the order of 1e-14 (around numerical precision), giving rise to differences in eigenvalues between the old and new versions also on the order of 1e-14. This is mostly expected behavior for 64bit floats and hopefully should not affect any prior results.

2024-08-07 04:13 UTC, Phionx approved these changes
LGTM!

2024-08-07 04:15 UTC, merged